# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy container app to Azure Web App - vTestWebApp

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: 'ubuntu-latest'
    strategy:
      matrix:
        java: [ '17' ]

    steps:
    - uses: actions/checkout@v2      
    - name: Set up JDK ${{matrix.java}}
      uses: actions/setup-java@v2
      with:
          java-version: ${{matrix.java}}
          distribution: 'adopt'
          cache: maven
    - name: Build with Maven Wrapper
      run: ./mvnw -B package

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Log in to registry
      uses: docker/login-action@v2
      with:
        registry: https://index.docker.io/v1/
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Build and push container image to registry
      uses: docker/build-push-action@v3
      with:
        push: true
        tags: index.docker.io/${{ secrets.AzureAppService_ContainerUsername_52a55fcd5dde46f5940a9171c0ceb789 }}/venkatesh01docker/clockbox:latest
        file: ./Dockerfile

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
    - name: Deploy to Azure Web App
      id: deploy-to-webapp
      uses: azure/webapps-deploy@v2
      with:
        app-name: 'vTestWebApp'
        slot-name: 'production'
        publish-profile: ${{ secrets.AzureAppService_PublishProfile_a144b52c1a04498fa8f4b6bc21dbc56b }}
        images: 'index.docker.io/${{ secrets.DOCKERHUB_USERNAME }}/venkatesh01docker/clockbox:${{ github.sha }}'
